<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas [
    <!ELEMENT personas (alumno*, profesor*)>
        <!ELEMENT alumno (nombre, apellido, curso, ciudad?)>
            <!ATTLIST alumno forma_pago (Bizum|Tarjeta|Contado) "Bizum">
            <!ATTLIST alumno mayor_de_edad (Si|No) "Si">
            <!ATTLIST alumno sexo (M|F) "M">
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT apellido (#PCDATA)>
            <!ELEMENT curso (#PCDATA)>
            <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT profesor (nombre, asignaturas)>
            <!ELEMENT asignaturas (asignatura*)>
                <!ELEMENT asignatura (#PCDATA)>
                    <!ATTLIST asignatura cod CDATA #REQUIRED>
]>

<personas>
    <alumno forma_pago="Bizum" mayor_de_edad="Si" sexo="M">
        <nombre>
            Pablo
        </nombre>

        <apellido>
            Merida
        </apellido>

        <curso>
            1º Daw
        </curso>

        <ciudad>
            Córdoba
        </ciudad>

    </alumno>
    <alumno>
        <nombre>
            Guille
        </nombre>

        <apellido>
            Serrano
        </apellido>

        <curso>
            1º Daw
        </curso>

    </alumno>
    <profesor>
        <nombre>
            Jose
        </nombre>

        <asignaturas>
            <asignatura cod="LM">
                Lenguaje de marcas
            </asignatura>
            <asignatura cod="BD">
                Base de datos
            </asignatura>
        </asignaturas>
    </profesor>
</personas>