<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errores[
<!ELEMENT errores (ejercicio+)>
    <!ELEMENT ejercicio (nombre, error*)>
        <!ATTLIST ejercicio id ID #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT error (linea, descripcion)>
            <!ELEMENT descripcion (#PCDATA)>
            <!ELEMENT linea (#PCDATA)>
            <!ATTLIST error fecha CDATA #IMPLIED>
            <!ATTLIST error hora CDATA #IMPLIED>

]>
<errores>
    <ejercicio id="ej1">
      <nombre>etiqueta</nombre>
      <error fecha="14/02/2022" hora="14:15">
        <linea>2</linea>
        <descripcion>DOCTYPE no declarado</descripcion>
      </error>
  
      <error>
        <linea>3</linea>
        <descripcion>No hay etiqueta ciudad</descripcion>
      </error>
  
    </ejercicio> 

      <ejercicio id="ej2">
        <nombre>agenda</nombre>
        <error>
          <linea>10</linea>
          <descripcion>
              Falta nodo raiz
          </descripcion>
        </error>
    
        <error>
          <linea>3</linea>
          <descripcion>No hay etiqueta ciudad</descripcion>
        </error>

        <error>
            <linea>8</linea>
            <descripcion>No se ha declarado el elemento tw</descripcion>
        </error>
        
        <error>
            <linea>4</linea>
            <descripcion>Modificar y a√±adir el elemento tw</descripcion>
        </error>
    
      </ejercicio>
  
  </errores>
