<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peliculas [
    <!ELEMENT peliculas (pelicula+)>
    <!ELEMENT pelicula (titulo | director | autor?)*>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
]>

<peliculas>
    <pelicula>
        <titulo>Con faldas y a lo loco</titulo>
        <director>Billy Wilder</director>
    </pelicula>
    <pelicula>
        <director>Leo McCarey</director>
        <titulo>Sopa de ganso</titulo>
        <autor>barto</autor>
    </pelicula>
</peliculas>